FROM python:3.12-bookworm

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

ENV UV_SYSTEM_PYTHON=1
